from shared.building_blocks import DomainException


class RejectedRequestIsFrozen(DomainException): ...


class ArchivedRequestIsFrozen(DomainException): ...


class PreferredVisitingTimeMustBeInsideQueueReceptionTime(DomainException): ...


class CannotCreateRequestToInactiveQueue(DomainException): ...


class TimePeriodNotValid(DomainException): ...
