services:
  # Additional
  core-postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${CORE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CORE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${CORE_POSTGRES_DB}
      - TZ=Europe/Moscow
    volumes:
      - core-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${CORE_POSTGRES_USER} -d ${CORE_POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  bot-postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${BOT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BOT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${BOT_POSTGRES_DB}
      - TZ=Europe/Moscow
    volumes:
      - bot-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${BOT_POSTGRES_USER} -d ${BOT_POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    restart: always
    # ports:
    #   - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  bot-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - bot-redis:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  adminer:
    image: adminer:5.4.1
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_SYSTEM=postgres
    ports:
      - "127.0.0.1:5050:8080"

  # Services

  core:
    build:
      context: services/core
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:5051:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AESSIV_HEX_KEY=${AESSIV_HEX_KEY}

      - POSTGRES_USER=${CORE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CORE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${CORE_POSTGRES_DB}
      - POSTGRES_HOST=core-postgres
      - POSTGRES_PORT=5432

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_LOGIN=${RABBITMQ_LOGIN}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

      - NOTIFICATIONS_BOT_USERNAME=${NOTIFICATIONS_BOT_USERNAME}
    depends_on:
      core-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  bot:
    build:
      context: services/telegram_notification
      dockerfile: Dockerfile
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AESSIV_HEX_KEY=${AESSIV_HEX_KEY}
      - BOT_TOKEN=${BOT_TOKEN}

      - POSTGRES_USER=${BOT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BOT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${BOT_POSTGRES_DB}
      - POSTGRES_HOST=bot-postgres
      - POSTGRES_PORT=5432

      - REDIS_HOST=bot-redis
      - REDIS_PORT=6379
      - REDIS_DB=0

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_LOGIN=${RABBITMQ_LOGIN}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      bot-redis:
        condition: service_started
      bot-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  core-postgres-data:
  bot-postgres-data:
  rabbitmq-data:
  bot-redis:
