from shared.building_blocks import DomainException


class CannotDeactivateAlreadyDeactivatedQueue(DomainException): ...


class CannotActivateActiveQueue(DomainException): ...


class TimePeriodNotValid(DomainException): ...


class NotConsistentFields(DomainException): ...


class RequestIsNotPending(DomainException): ...


class TimeMustBeInsideQueueReceptionTime(DomainException): ...


class RequestNotFound(DomainException): ...


class RequestIsFrozen(DomainException): ...


class CannotScheduleRequest(DomainException): ...
