from shared.building_blocks import DomainError


class CannotDeactivateAlreadyDeactivatedQueue(DomainError): ...


class CannotActivateActiveQueue(DomainError): ...


class TimePeriodNotValid(DomainError): ...


class NotConsistentFields(DomainError): ...
