from typing import Protocol
from modules.user.domain.aggregates import User, UserId
from modules.user.domain.value_objects import Email


class IUserRepository(Protocol):
    async def save(self, user: User) -> None: ...
    async def delete(self, user: User | UserId) -> None: ...
    async def exists_by_id(self, user_id: UserId) -> bool: ...
    async def exists_by_email(self, user_id: Email) -> bool: ...
    async def find_by_id(self, user_id: UserId) -> User | None: ...
    async def find_by_email(self, email: Email) -> User | None: ...
