from shared.building_blocks import DomainError


class WeakPasswordError(DomainError): ...


class InvalidPasswordError(DomainError): ...


class SamePasswordError(DomainError): ...


class SameEmailError(DomainError): ...
