"""Added queue persistence

Revision ID: 27dd3677fdd7
Revises:
Create Date: 2025-11-03 22:10:15.509310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27dd3677fdd7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS user_schema")
    op.execute("CREATE SCHEMA IF NOT EXISTS queue_schema")
    op.create_table(
        "queue",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("clean_up_period_days", sa.Integer(), nullable=False),
        sa.Column("reception_time_start", sa.Time(), nullable=False),
        sa.Column("reception_time_end", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="queue_schema",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("patronymic", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="user_schema",
    )
    op.create_table(
        "request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("queue_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_date", sa.Date(), nullable=False),
        sa.Column("preferred_time_start", sa.Time(), nullable=False),
        sa.Column("preferred_time_end", sa.Time(), nullable=False),
        sa.Column("confirmed_date", sa.Date(), nullable=True),
        sa.Column("confirmed_time_start", sa.Time(), nullable=True),
        sa.Column("confirmed_time_end", sa.Time(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queue_schema.queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="queue_schema",
    )
    op.create_table(
        "telegram_user",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
        schema="user_schema",
    )
    op.create_table(
        "request_status_history_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["queue_schema.request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="queue_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_status_history_item", schema="queue_schema")
    op.drop_table("telegram_user", schema="user_schema")
    op.drop_table("request", schema="queue_schema")
    op.drop_table("user", schema="user_schema")
    op.drop_table("queue", schema="queue_schema")
    op.execute("DROP SCHEMA IF EXISTS queue_schema")
    op.execute("DROP SCHEMA IF EXISTS user_schema")
    # ### end Alembic commands ###
