"""Add index

Revision ID: 2b346f741c0f
Revises: 27dd3677fdd7
Create Date: 2025-11-22 18:39:26.942007

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2b346f741c0f"
down_revision: Union[str, Sequence[str], None] = "27dd3677fdd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_queue_schema_queue_owner_id"),
        "queue",
        ["owner_id"],
        unique=False,
        schema="queue_schema",
    )
    op.create_index(
        op.f("ix_queue_schema_request_queue_id"),
        "request",
        ["queue_id"],
        unique=False,
        schema="queue_schema",
    )
    op.create_index(
        op.f("ix_queue_schema_request_user_id"),
        "request",
        ["user_id"],
        unique=False,
        schema="queue_schema",
    )
    op.create_index(
        op.f("ix_queue_schema_request_status_history_item_request_id"),
        "request_status_history_item",
        ["request_id"],
        unique=False,
        schema="queue_schema",
    )
    op.create_index(
        op.f("ix_user_schema_telegram_user_user_id"),
        "telegram_user",
        ["user_id"],
        unique=False,
        schema="user_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_schema_telegram_user_user_id"),
        table_name="telegram_user",
        schema="user_schema",
    )
    op.drop_index(
        op.f("ix_queue_schema_request_status_history_item_request_id"),
        table_name="request_status_history_item",
        schema="queue_schema",
    )
    op.drop_index(
        op.f("ix_queue_schema_request_user_id"),
        table_name="request",
        schema="queue_schema",
    )
    op.drop_index(
        op.f("ix_queue_schema_request_queue_id"),
        table_name="request",
        schema="queue_schema",
    )
    op.drop_index(
        op.f("ix_queue_schema_queue_owner_id"),
        table_name="queue",
        schema="queue_schema",
    )
    # ### end Alembic commands ###
