"""Add priority to queue.request

Revision ID: 2b9ccce235fa
Revises: c7236dfd28b8
Create Date: 2025-12-13 19:32:54.472326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9ccce235fa'
down_revision: Union[str, Sequence[str], None] = 'c7236dfd28b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('priority', sa.String(length=50), nullable=False), schema='queue_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'priority', schema='queue_schema')
    # ### end Alembic commands ###
