"""Nullable request confirmation datetime

Revision ID: 85c37fad00e2
Revises: 2b9ccce235fa
Create Date: 2025-12-14 00:10:23.300538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85c37fad00e2"
down_revision: Union[str, Sequence[str], None] = "2b9ccce235fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request_confirmation_datetime_history_item",
        "date",
        existing_type=sa.DATE(),
        nullable=True,
        schema="request_schema",
    )
    op.alter_column(
        "request_confirmation_datetime_history_item",
        "time_start",
        existing_type=postgresql.TIME(),
        nullable=True,
        schema="request_schema",
    )
    op.alter_column(
        "request_confirmation_datetime_history_item",
        "time_end",
        existing_type=postgresql.TIME(),
        nullable=True,
        schema="request_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request_confirmation_datetime_history_item",
        "time_end",
        existing_type=postgresql.TIME(),
        nullable=False,
        schema="request_schema",
    )
    op.alter_column(
        "request_confirmation_datetime_history_item",
        "time_start",
        existing_type=postgresql.TIME(),
        nullable=False,
        schema="request_schema",
    )
    op.alter_column(
        "request_confirmation_datetime_history_item",
        "date",
        existing_type=sa.DATE(),
        nullable=False,
        schema="request_schema",
    )
    # ### end Alembic commands ###
