"""Remove request status

Revision ID: abf536cd9bad
Revises: 2b346f741c0f
Create Date: 2025-12-06 23:52:37.016118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "abf536cd9bad"
down_revision: Union[str, Sequence[str], None] = "2b346f741c0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_queue_schema_request_status_history_item_request_id"),
        table_name="request_status_history_item",
        schema="queue_schema",
    )
    op.drop_table("request_status_history_item", schema="queue_schema")
    op.add_column(
        "request",
        sa.Column("status", sa.String(length=50), nullable=False),
        schema="queue_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("request", "status", schema="queue_schema")
    op.create_table(
        "request_status_history_item",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("request_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["queue_schema.request.id"],
            name=op.f("request_status_history_item_request_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("request_status_history_item_pkey")),
        schema="queue_schema",
    )
    op.create_index(
        op.f("ix_queue_schema_request_status_history_item_request_id"),
        "request_status_history_item",
        ["request_id"],
        unique=False,
        schema="queue_schema",
    )
    # ### end Alembic commands ###
