"""Add request models

Revision ID: c7236dfd28b8
Revises: abf536cd9bad
Create Date: 2025-12-12 00:04:48.991014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7236dfd28b8"
down_revision: Union[str, Sequence[str], None] = "abf536cd9bad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS request_schema")
    op.create_table(
        "queue",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reception_time_start", sa.Time(), nullable=False),
        sa.Column("reception_time_end", sa.Time(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_queue_owner_id"),
        "queue",
        ["owner_id"],
        unique=False,
        schema="request_schema",
    )
    op.create_table(
        "request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("queue_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=1000), nullable=False),
        sa.Column("preferred_date", sa.Date(), nullable=False),
        sa.Column("preferred_time_start", sa.Time(), nullable=False),
        sa.Column("preferred_time_end", sa.Time(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["request_schema.queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_request_queue_id"),
        "request",
        ["queue_id"],
        unique=False,
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_request_user_id"),
        "request",
        ["user_id"],
        unique=False,
        schema="request_schema",
    )
    op.create_table(
        "request_comment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["request_schema.request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_request_comment_request_id"),
        "request_comment",
        ["request_id"],
        unique=False,
        schema="request_schema",
    )
    op.create_table(
        "request_confirmation_datetime_history_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time_start", sa.Time(), nullable=False),
        sa.Column("time_end", sa.Time(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["request_schema.request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_request_confirmation_datetime_history_item_request_id"),
        "request_confirmation_datetime_history_item",
        ["request_id"],
        unique=False,
        schema="request_schema",
    )
    op.create_table(
        "request_priority_history_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["request_schema.request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_request_priority_history_item_request_id"),
        "request_priority_history_item",
        ["request_id"],
        unique=False,
        schema="request_schema",
    )
    op.create_table(
        "request_status_history_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["request_schema.request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="request_schema",
    )
    op.create_index(
        op.f("ix_request_schema_request_status_history_item_request_id"),
        "request_status_history_item",
        ["request_id"],
        unique=False,
        schema="request_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_request_schema_request_status_history_item_request_id"),
        table_name="request_status_history_item",
        schema="request_schema",
    )
    op.drop_table("request_status_history_item", schema="request_schema")
    op.drop_index(
        op.f("ix_request_schema_request_priority_history_item_request_id"),
        table_name="request_priority_history_item",
        schema="request_schema",
    )
    op.drop_table("request_priority_history_item", schema="request_schema")
    op.drop_index(
        op.f("ix_request_schema_request_confirmation_datetime_history_item_request_id"),
        table_name="request_confirmation_datetime_history_item",
        schema="request_schema",
    )
    op.drop_table("request_confirmation_datetime_history_item", schema="request_schema")
    op.drop_index(
        op.f("ix_request_schema_request_comment_request_id"),
        table_name="request_comment",
        schema="request_schema",
    )
    op.drop_table("request_comment", schema="request_schema")
    op.drop_index(
        op.f("ix_request_schema_request_user_id"),
        table_name="request",
        schema="request_schema",
    )
    op.drop_index(
        op.f("ix_request_schema_request_queue_id"),
        table_name="request",
        schema="request_schema",
    )
    op.drop_table("request", schema="request_schema")
    op.drop_index(
        op.f("ix_request_schema_queue_owner_id"),
        table_name="queue",
        schema="request_schema",
    )
    op.drop_table("queue", schema="request_schema")
    op.execute("DROP SCHEMA IF EXISTS request_schema")
    # ### end Alembic commands ###
