"""Initialize models

Revision ID: ba53355eb74f
Revises: 
Create Date: 2025-12-21 23:33:10.344180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba53355eb74f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index(op.f('ix_queues_owner_id'), 'queues', ['owner_id'], unique=False)
    op.create_table('telegram_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_telegram_users_telegram_id'), 'telegram_users', ['telegram_id'], unique=True)
    op.create_table('requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=1000), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time_start', sa.Time(), nullable=False),
    sa.Column('preferred_time_end', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.queue_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_requests_queue_id'), 'requests', ['queue_id'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_queue_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_telegram_users_telegram_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index(op.f('ix_queues_owner_id'), table_name='queues')
    op.drop_table('queues')
    # ### end Alembic commands ###
