name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm ci
        working-directory: additional/client
      
      - name: Build frontend
        run: npm run build
        working-directory: additional/client
      
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy/client
          cp -r additional/client/dist/* deploy/client/
          cp -r services deploy/
          cp docker-compose.yaml deploy/

      - name: Archive code for deploy
        run: |
          cd deploy
          zip -r ../deploy.zip . -x '*.git*' '*.github/*'

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "AESSIV_HEX_KEY=${{ secrets.AESSIV_HEX_KEY }}" >> .env

          echo "CORE_POSTGRES_USER=${{ secrets.CORE_POSTGRES_USER }}" >> .env
          echo "CORE_POSTGRES_PASSWORD=${{ secrets.CORE_POSTGRES_PASSWORD }}" >> .env
          echo "CORE_POSTGRES_DB=${{ secrets.CORE_POSTGRES_DB }}" >> .env
          
          echo "NOTIFICATIONS_BOT_USERNAME=${{ vars.NOTIFICATIONS_BOT_USERNAME }}" >> .env
          echo "ALLOW_ORIGIN_REGEX=$(echo "${{ vars.ALLOW_ORIGIN_REGEX_BASE64 }}" | base64 -d)" >> .env

          echo "BOT_POSTGRES_USER=${{ secrets.BOT_POSTGRES_USER }}" >> .env
          echo "BOT_POSTGRES_PASSWORD=${{ secrets.BOT_POSTGRES_PASSWORD }}" >> .env
          echo "BOT_POSTGRES_DB=${{ secrets.BOT_POSTGRES_DB }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

          echo "RABBITMQ_LOGIN=${{ secrets.RABBITMQ_LOGIN }}" >> .env
          echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" >> .env

      - name: Transfer files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "deploy.zip,.env"
          target: "/home/${{ secrets.SERVER_USER }}/OnlineQueue/"

  build:
    runs-on: ubuntu-latest
    needs: build-and-copy
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/OnlineQueue/
            unzip -o deploy.zip
            sudo docker compose build
            sudo docker compose down
            sudo docker compose up -d --remove-orphans
            sudo docker image prune -f
            rm deploy.zip